# Render.com Blueprint for Zelcry (SQLite version)
# Deploy with one click: https://render.com/docs/blueprint-spec

services:
  # Django Web Service (no external database)
  - type: web
    name: zelcry
    env: python
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind=0.0.0.0:$PORT --workers=4 --timeout=120 zelcry.wsgi:application"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: CRYPTOCOMPARE_API_KEY
        sync: false  # Optional: Set manually in Render dashboard
